window.__BRIEFING_DATA__ = {
  "metadata": {
    "title": "글로벌 매크로 & 경제 모닝 브리핑",
    "updated_at": "2026-08-25 06:55:33",
    "date_str": "2026년 08월 25일 (화)",
    "indicator_count": 19,
    "news_count": 22
  },
  "indicators": [
    {
      "id": "us_short",
      "symbol": "^IRX",
      "name_ko": "미국 단기 국채 금리 (13주)",
      "name_en": "US 13W T-Bill",
      "group": "macro",
      "unit": "%",
      "format": "{:.3f}%",
      "description": "단기 무위험 금리 및 연준의 기준금리 방향성을 가장 빠르게 선반영하는 단기채 지표",
      "price": 3.703,
      "previous_close": 3.697,
      "change": 0.006,
      "change_percent": 0.16,
      "display_price": "3.703%",
      "status": "up",
      "history": [
        3.697,
        3.703,
        3.705,
        3.7,
        3.703,
        3.71,
        3.703
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EIRX/",
      "updated_at": "2026-08-24 21:55:16"
    },
    {
      "id": "us10y",
      "symbol": "^TNX",
      "name_ko": "미국 10년물 국채 금리",
      "name_en": "US 10Y Yield",
      "group": "macro",
      "unit": "%",
      "has_yield_signal": true,
      "format": "{:.3f}%",
      "description": "글로벌 무위험 금리 벤치마크, 밸류에이션 및 유동성 바로미터 (5% 돌파 시 경계 경보)",
      "price": 4.704,
      "previous_close": 4.696,
      "change": 0.008,
      "change_percent": 0.17,
      "display_price": "4.704%",
      "status": "up",
      "history": [
        4.696,
        4.724,
        4.706,
        4.653,
        4.696,
        4.738,
        4.704
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ETNX/",
      "updated_at": "2026-08-24 21:55:16",
      "yield_signal": {
        "level": "warn",
        "tag": "🟠 주의 구간 (4.50~5.00%)",
        "desc": "주식 밸류에이션 부담 & 환율 상승 압력"
      }
    },
    {
      "id": "us30y",
      "symbol": "^TYX",
      "name_ko": "미국 30년물 국채 금리",
      "name_en": "US 30Y Yield",
      "group": "macro",
      "unit": "%",
      "format": "{:.3f}%",
      "description": "초장기 채권 금리, 미국의 막대한 재정적자 및 기간 프리미엄(Term Premium) 바로미터",
      "price": 5.231,
      "previous_close": 5.265,
      "change": -0.034,
      "change_percent": -0.65,
      "display_price": "5.231%",
      "status": "down",
      "history": [
        5.265,
        5.309,
        5.285,
        5.194,
        5.237,
        5.276,
        5.231
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ETYX/",
      "updated_at": "2026-08-24 21:55:16"
    },
    {
      "id": "dxy",
      "symbol": "DX-Y.NYB",
      "name_ko": "달러 인덱스 (DXY)",
      "name_en": "US Dollar Index",
      "group": "macro",
      "unit": "pt",
      "format": "{:.2f} pt",
      "description": "주요 6개국 통화 대비 달러화 가치 (달러 강세/약세 지표)",
      "price": 98.984,
      "previous_close": 99.64,
      "change": -0.656,
      "change_percent": -0.66,
      "display_price": "98.98 pt",
      "status": "down",
      "history": [
        99.64,
        99.65,
        98.83,
        98.9,
        98.8,
        98.984
      ],
      "chart_url": "https://finance.yahoo.com/quote/DX-Y.NYB/",
      "updated_at": "2026-08-24 21:55:16"
    },
    {
      "id": "usdjpy",
      "symbol": "JPY=X",
      "name_ko": "달러 / 엔 환율 (USD/JPY)",
      "name_en": "USD / JPY",
      "group": "macro",
      "unit": "엔",
      "format": "{:,.2f}엔",
      "description": "엔 캐리 트레이드 청산 리스크 및 일본은행(BOJ) 통화정책 바로미터",
      "price": 159.076,
      "previous_close": 159.426,
      "change": -0.35,
      "change_percent": -0.22,
      "display_price": "159.08엔",
      "status": "down",
      "history": [
        159.223,
        159.34,
        159.55,
        158.276,
        158.883,
        158.904,
        159.076
      ],
      "chart_url": "https://finance.yahoo.com/quote/JPY%3DX/",
      "updated_at": "2026-08-24 21:55:17"
    },
    {
      "id": "gold",
      "symbol": "GC=F",
      "name_ko": "국제 금 시세 (선물)",
      "name_en": "Gold Futures",
      "group": "macro",
      "unit": "$",
      "format": "${:,.2f}",
      "description": "인플레이션 헤지 및 대표 닻(Anchor) 안전자산, 실질금리 역방향 흐름",
      "price": 4710.0,
      "previous_close": 4417.8,
      "change": 292.2,
      "change_percent": 6.61,
      "display_price": "$4,710.00",
      "status": "up",
      "history": [
        4417.8,
        4366.0,
        4489.4,
        4516.3,
        4624.1,
        4710.0
      ],
      "chart_url": "https://finance.yahoo.com/quote/GC%3DF/",
      "updated_at": "2026-08-24 21:55:17"
    },
    {
      "id": "wti",
      "symbol": "CL=F",
      "name_ko": "국제 유가 (WTI 원유)",
      "name_en": "WTI Crude Oil",
      "group": "macro",
      "unit": "$",
      "format": "${:.2f}",
      "description": "헤드라인 인플레이션 시한폭탄 및 원자재 물가 압력 지표",
      "price": 84.98,
      "previous_close": 84.5,
      "change": 0.48,
      "change_percent": 0.57,
      "display_price": "$84.98",
      "status": "up",
      "history": [
        84.5,
        84.94,
        85.83,
        87.83,
        87.06,
        84.98
      ],
      "chart_url": "https://finance.yahoo.com/quote/CL%3DF/",
      "updated_at": "2026-08-24 21:55:17"
    },
    {
      "id": "btc",
      "symbol": "BTC-USD",
      "name_ko": "비트코인 (BTC)",
      "name_en": "Bitcoin",
      "group": "macro",
      "unit": "$",
      "format": "${:,.0f}",
      "description": "글로벌 위험자산 선호도 및 잉여 유동성 측정 지표",
      "price": 78930.32,
      "previous_close": 64680.71,
      "change": 14249.61,
      "change_percent": 22.03,
      "display_price": "$78,930",
      "status": "up",
      "history": [
        64680.711,
        69266.188,
        73032.758,
        78335.188,
        77083.414,
        77755.266,
        78930.32
      ],
      "chart_url": "https://finance.yahoo.com/quote/BTC-USD/",
      "updated_at": "2026-08-24 21:55:17"
    },
    {
      "id": "tga",
      "symbol": "TGA Balance",
      "name_ko": "미 재무부 TGA 현금 잔고",
      "name_en": "US Treasury General Account",
      "group": "macro",
      "unit": "$",
      "is_tga": true,
      "format": "${:,.1f}B",
      "description": "스콧 베센트 재무장관의 유동성 탄약고 (잔고 방출=유동성 공급/주가상승, 충전=유동성 흡수)",
      "price": 935.1,
      "previous_close": 15.8,
      "change": 919.3,
      "change_percent": 0.0,
      "display_price": "$935.1B (약 9,351억$)",
      "status": "up",
      "history": [
        296.8,
        295.5,
        936.4,
        933.2,
        17.6,
        15.8,
        935.1
      ],
      "chart_url": "https://fiscaldata.treasury.gov/datasets/daily-treasury-statement/operating-cash-balance",
      "updated_at": "2026-08-24 21:55:18"
    },
    {
      "id": "sp500",
      "symbol": "^GSPC",
      "name_ko": "S&P 500 지수",
      "name_en": "S&P 500",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "미국 대형주 대표 벤치마크 및 글로벌 주식 투자 심리",
      "price": 7652.86,
      "previous_close": 7798.99,
      "change": -146.13,
      "change_percent": -1.87,
      "display_price": "7,652.86",
      "status": "down",
      "history": [
        7785.76,
        7745.06,
        7691.76,
        7707.98,
        7641.16,
        7674.37,
        7652.86
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EGSPC/",
      "updated_at": "2026-08-24 21:55:18"
    },
    {
      "id": "nasdaq",
      "symbol": "^NDX",
      "name_ko": "나스닥 100 지수",
      "name_en": "Nasdaq 100",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "빅테크 및 성장주 중심의 글로벌 기술주 지표",
      "price": 29023.182,
      "previous_close": 30084.5,
      "change": -1061.318,
      "change_percent": -3.53,
      "display_price": "29,023.18",
      "status": "down",
      "history": [
        30046.141,
        29995.381,
        29490.961,
        29426.02,
        29213.16,
        29308.859,
        29023.182
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ENDX/",
      "updated_at": "2026-08-24 21:55:19"
    },
    {
      "id": "sox",
      "symbol": "^SOX",
      "name_ko": "필라델피아 반도체 지수",
      "name_en": "PHLX Semiconductor",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "글로벌 AI/반도체 밸류체인 및 삼성전자/SK하이닉스 외국인 수급 직결",
      "price": 11423.169,
      "previous_close": 12456.0,
      "change": -1032.831,
      "change_percent": -8.29,
      "display_price": "11,423.17",
      "status": "down",
      "history": [
        12417.05,
        12621.0,
        11992.46,
        11738.23,
        11800.02,
        11740.37,
        11423.169
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ESOX/",
      "updated_at": "2026-08-24 21:55:19"
    },
    {
      "id": "vix",
      "symbol": "^VIX",
      "name_ko": "VIX 변동성 지수 (공포지수)",
      "name_en": "CBOE Volatility",
      "group": "us_market",
      "unit": "pt",
      "format": "{:.2f}",
      "description": "월가 S&P500 옵션 내재 변동성 및 투자자 공포/탐욕 심리",
      "price": 15.85,
      "previous_close": 14.25,
      "change": 1.6,
      "change_percent": 11.23,
      "display_price": "15.85",
      "status": "up",
      "history": [
        14.25,
        15.19,
        15.84,
        14.89,
        16.01,
        15.13,
        15.85
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EVIX/",
      "updated_at": "2026-08-24 21:55:19"
    },
    {
      "id": "usdkrw",
      "symbol": "KRW=X",
      "name_ko": "달러 / 원 환율",
      "name_en": "USD / KRW",
      "group": "korea_market",
      "unit": "원",
      "has_fx_averages": true,
      "format": "{:,.2f}원",
      "description": "원화 가치 및 외인 수급의 핵심 변수 (1년 평균 및 3년 평균 기준선 제공)",
      "price": 1382.28,
      "previous_close": 1416.85,
      "change": -34.57,
      "change_percent": -2.44,
      "display_price": "1,382.28원",
      "status": "down",
      "history": [
        1415.37,
        1414.73,
        1413.58,
        1389.4,
        1390.79,
        1384.98,
        1382.28
      ],
      "chart_url": "https://finance.yahoo.com/quote/KRW%3DX/",
      "updated_at": "2026-08-24 21:55:19",
      "fx_averages": {
        "avg_1y": 1460.6,
        "avg_3y": 1401.1
      }
    },
    {
      "id": "kospi",
      "symbol": "^KS11",
      "name_ko": "코스피 종합지수 (KOSPI)",
      "name_en": "KOSPI Composite",
      "group": "korea_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "국내 대형주/제조업 중심 유가증권시장 대표 벤치마크",
      "price": 6696.96,
      "previous_close": 6579.04,
      "change": 117.92,
      "change_percent": 1.79,
      "display_price": "6,696.96",
      "status": "up",
      "history": [
        6813.34,
        6977.94,
        6869.83,
        6471.17,
        6852.58,
        6912.95
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EKS11/",
      "updated_at": "2026-08-24 21:55:20"
    },
    {
      "id": "kosdaq",
      "symbol": "^KQ11",
      "name_ko": "코스닥 종합지수 (KOSDAQ)",
      "name_en": "KOSDAQ Composite",
      "group": "korea_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "국내 IT, 바이오, 2차전지, 중소형 성장주 대표 벤치마크",
      "price": 813.33,
      "previous_close": 858.91,
      "change": -45.58,
      "change_percent": -5.31,
      "display_price": "813.33",
      "status": "down",
      "history": [
        861.37,
        864.65,
        834.2,
        824.46,
        840.89,
        801.94
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EKQ11/",
      "updated_at": "2026-08-24 21:55:20"
    },
    {
      "id": "kr_bond3y",
      "symbol": "KR-BOND 3Y",
      "name_ko": "한국 국고채 3년물 금리",
      "name_en": "Korea Treasury 3Y",
      "group": "korea_market",
      "unit": "%",
      "is_kr_bond": true,
      "format": "{:.2f}%",
      "description": "국내 채권시장 단기 기준물, 한국은행 통화정책 및 기업 자금조달 금리 벤치마크",
      "price": 3.83,
      "previous_close": 3.85,
      "change": -0.02,
      "change_percent": -0.52,
      "display_price": "3.83%",
      "status": "down",
      "history": [
        3.78,
        3.79,
        3.84,
        3.79,
        3.81,
        3.85,
        3.83
      ],
      "chart_url": "https://finance.naver.com/marketindex/interestDetail.naver?marketindexCd=IRR_GOVT03Y",
      "updated_at": "2026-08-24 21:55:20"
    },
    {
      "id": "kr_bond10y",
      "symbol": "KR-BOND 10Y",
      "name_ko": "한국 국고채 10년물 금리",
      "name_en": "Korea Treasury 10Y",
      "group": "korea_market",
      "unit": "%",
      "is_kr_bond10y": true,
      "has_kr_yield_signal": true,
      "format": "{:.3f}%",
      "description": "국내 장기 무위험 금리 벤치마크 (4.0% 경계 / 4.5% 대피 / 5.0% 위기)",
      "price": 4.366,
      "previous_close": 4.334,
      "change": 0.032,
      "change_percent": 0.74,
      "display_price": "4.366%",
      "status": "up",
      "history": [
        4.28,
        4.3,
        4.32,
        4.34,
        4.35,
        4.366
      ],
      "chart_url": "https://kr.investing.com/rates-bonds/south-korea-10-year-bond-yield",
      "updated_at": "2026-08-24 21:55:21"
    },
    {
      "id": "ewy",
      "symbol": "EWY",
      "name_ko": "MSCI 한국 ETF (EWY)",
      "name_en": "iShares MSCI S.Korea",
      "group": "korea_market",
      "unit": "$",
      "format": "${:.2f}",
      "description": "뉴욕 야간 외국인 한국물 거래 (익일 아침 코스피 시초가 선행 지표)",
      "price": 173.64,
      "previous_close": 178.62,
      "change": -4.98,
      "change_percent": -2.79,
      "display_price": "$173.64",
      "status": "down",
      "history": [
        179.74,
        185.1,
        170.05,
        174.43,
        178.16,
        178.34,
        173.64
      ],
      "chart_url": "https://finance.yahoo.com/quote/EWY/",
      "updated_at": "2026-08-24 21:55:21"
    }
  ],
  "news": [
    {
      "source": "연합인포맥스",
      "title_ko": "[외환-주간] 한미 통화정책에 촉각…월말 수급 지형 변할까",
      "title_en": "",
      "summary_ko": "[외환-주간] 한미 통화정책에 촉각…월말 수급 지형 변할까 연합인포맥스. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE44bXZjd1prUk83YjNIel9zMXZlY0MxQWtDWGRHcGgtaVZjSVdhMmNyN0FqZTN5bl9STjB1OWExaG40R2RyRHNRSVVDOGRYRmJRdS0xWWQyWnJ6a0U4cWV2bnNCTk1UTjd2cDFyY0RaUmc?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE44bXZjd1prUk83YjNIel9zMXZlY0MxQWtDWGRHcGgtaVZjSVdhMmNyN0FqZTN5bl9STjB1OWExaG40R2RyRHNRSVVDOGRYRmJRdS0xWWQyWnJ6a0U4cWV2bnNCTk1UTjd2cDFyY0RaUmc?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Sun, 23 Aug 2026 04:00:14 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "[다시쓰는 잠재성장률③] 통화정책 영향은…\"보다 높은 금리 정당화\" |",
      "title_en": "",
      "summary_ko": "[다시쓰는 잠재성장률③] 통화정책 영향은…\"보다 높은 금리 정당화\" | 연합인포맥스. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1jakhJMjEzcjNERVNBSTd5NmFRVzNEZkc4R2dFVld4M3RwMjBSc1FLRjRUWlFJQV8yYzljMVVHaU54VklsdS1hcExrMFlVcXQ4RFlURVVILXlWQ0JQZ1ZxRElGQnE5U2R2SkFfWmR5N1dkNkxU?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1jakhJMjEzcjNERVNBSTd5NmFRVzNEZkc4R2dFVld4M3RwMjBSc1FLRjRUWlFJQV8yYzljMVVHaU54VklsdS1hcExrMFlVcXQ4RFlURVVILXlWQ0JQZ1ZxRElGQnE5U2R2SkFfWmR5N1dkNkxU?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 06:15:47 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "한국경제",
      "title_ko": "매매·전월세 모두 뛴 서울…원인은 유동성 급증",
      "title_en": "",
      "summary_ko": "매매·전월세 모두 뛴 서울…원인은 유동성 급증 한국경제. 중앙은행 통화정책 기조 및 글로벌 잉여 유동성 흐름의 변화를 나타내는 주요 매크로 시그널입니다. 한국경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1sclVDcTdPdGdheGNpTjRHWnF1elQ4QkxPMDlORm5aNmdSUkkyOVdJdEdZaVV5QXZjTXg0ZmVDUzlMWEs0RmdiS09lNUlQMzBUWVZjOGU3ak5kQQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1sclVDcTdPdGdheGNpTjRHWnF1elQ4QkxPMDlORm5aNmdSUkkyOVdJdEdZaVV5QXZjTXg0ZmVDUzlMWEs0RmdiS09lNUlQMzBUWVZjOGU3ak5kQQ?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 10:01:07 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "매일경제",
      "title_ko": "투어스 ‘SODA SODA’ 카리나·연준→日 톱스타까지…챌린지 열풍",
      "title_en": "",
      "summary_ko": "투어스 ‘SODA SODA’ 카리나·연준→日 톱스타까지…챌린지 열풍 매일경제. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 매일경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFAwMlMzOU9vcHpFWTFGaXhQa3VWQWZ2NXhEM0loT3E3dzI3eVViUlhKcWczbFJBRDFhSUo5d0ZKSm40Y0NlekVBYXBXZTJvZw?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFAwMlMzOU9vcHpFWTFGaXhQa3VWQWZ2NXhEM0loT3E3dzI3eVViUlhKcWczbFJBRDFhSUo5d0ZKSm40Y0NlekVBYXBXZTJvZw?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 04:56:05 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "트럼프 \"호르무즈 해협, 현재 미국 영토\"",
      "title_en": "",
      "summary_ko": "트럼프 \"호르무즈 해협, 현재 미국 영토\" 연합인포맥스. 중동 및 동유럽 지정학적 긴장 고조에 따른 국제 유가·원자재 공급망 충격과 인플레이션 재점화 가능성에 유의할 필요가 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBpaExLRjB5ZUdIZ1ZOV0p4X2otVEpRVEJOTWY4ZUY5TF83S2NucmVvNk1Ldk5jeHpndGxQejgzbVgyLURES3ZONkltVTI5MlVIazRUUW9TN21nN2RYYzRyampvVVlKM1lYSldQM1l4aVQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBpaExLRjB5ZUdIZ1ZOV0p4X2otVEpRVEJOTWY4ZUY5TF83S2NucmVvNk1Ldk5jeHpndGxQejgzbVgyLURES3ZONkltVTI5MlVIazRUUW9TN21nN2RYYzRyampvVVlKM1lYSldQM1l4aVQ?oc=5",
      "category": "us_economy",
      "section_no": 3,
      "section_title": "미국 경제 관련 주요 뉴스 요약",
      "section_icon": "🇺🇸",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sat, 22 Aug 2026 06:47:33 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "트럼프 \"이란 합의할 준비 안 돼…'40조弗' 국가부채 성장이 쉽게 해결\"",
      "title_en": "",
      "summary_ko": "트럼프 \"이란 합의할 준비 안 돼…'40조弗' 국가부채 성장이 쉽게 해결\" 연합인포맥스. 미 재무부의 TGA 현금 잔고 방출과 40조 달러 국가부채 조달(QRA) 사이클에 따른 국채 기간 프리미엄 및 글로벌 달러 유동성 환경에 직접적인 영향을 미칠 수 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE16RWNBMGkyeV9EN2p2OTZKajhuVW1jNkRiU2Q2Zk1EcmhQME51RFphT25WX0U1dmprc1Etc3E0aU9rcm0yb0M4WTJkTTVDYjhxNk5QVENuTUNxbXQxTWROY21sWVN6OFlWbkpkdHpfbVE?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE16RWNBMGkyeV9EN2p2OTZKajhuVW1jNkRiU2Q2Zk1EcmhQME51RFphT25WX0U1dmprc1Etc3E0aU9rcm0yb0M4WTJkTTVDYjhxNk5QVENuTUNxbXQxTWROY21sWVN6OFlWbkpkdHpfbVE?oc=5",
      "category": "us_economy",
      "section_no": 3,
      "section_title": "미국 경제 관련 주요 뉴스 요약",
      "section_icon": "🇺🇸",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Fri, 21 Aug 2026 23:09:38 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "이란 대통령 \"美 가장 가혹하고 끔찍한 제재…우리 사회 많은 문제\"",
      "title_en": "",
      "summary_ko": "이란 대통령 \"美 가장 가혹하고 끔찍한 제재…우리 사회 많은 문제\" 연합인포맥스. 중동 및 동유럽 지정학적 긴장 고조에 따른 국제 유가·원자재 공급망 충격과 인플레이션 재점화 가능성에 유의할 필요가 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE8yMGh6M2t2M3BaYUtYQXF0UFJSWkpXNGlmdHFzV3J2ZUlRUFNzMEhzRVRTZzgxVUtPdUtPY2QwclpGUHlaS0ZIbFVLd0VKT1YzVUp6TWRLdkVuR3NRUXVaZE9obG1UcGNPbFVLUHloSjA?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE8yMGh6M2t2M3BaYUtYQXF0UFJSWkpXNGlmdHFzV3J2ZUlRUFNzMEhzRVRTZzgxVUtPdUtPY2QwclpGUHlaS0ZIbFVLd0VKT1YzVUp6TWRLdkVuR3NRUXVaZE9obG1UcGNPbFVLUHloSjA?oc=5",
      "category": "us_economy",
      "section_no": 3,
      "section_title": "미국 경제 관련 주요 뉴스 요약",
      "section_icon": "🇺🇸",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sun, 23 Aug 2026 18:19:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "언론 기고 통해 나온 베센트 이란 제재 예고편…CNN \"알맹이 없어\"",
      "title_en": "",
      "summary_ko": "언론 기고 통해 나온 베센트 이란 제재 예고편…CNN \"알맹이 없어\" 연합인포맥스. 미 재무부의 TGA 현금 잔고 방출과 40조 달러 국가부채 조달(QRA) 사이클에 따른 국채 기간 프리미엄 및 글로벌 달러 유동성 환경에 직접적인 영향을 미칠 수 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5idFI3Vmp1eG41Z3FITVJwWl9QOUIweEc5dDNmeWZHTkQ0MmNMTTlxRFN0R2tCR19PSmxES190Z0JrUGVnUW1MaTUyVzdWaFNMdDd2TmFpVFU1aF9rRnN5dDRYLTBrZWZYdHQ1eUNkV0U?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5idFI3Vmp1eG41Z3FITVJwWl9QOUIweEc5dDNmeWZHTkQ0MmNMTTlxRFN0R2tCR19PSmxES190Z0JrUGVnUW1MaTUyVzdWaFNMdDd2TmFpVFU1aF9rRnN5dDRYLTBrZWZYdHQ1eUNkV0U?oc=5",
      "category": "us_economy",
      "section_no": 3,
      "section_title": "미국 경제 관련 주요 뉴스 요약",
      "section_icon": "🇺🇸",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Mon, 24 Aug 2026 04:20:44 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "\"美 석유기업 공격하겠다\"…이란, 전례 없는 '민간 타깃' 위협",
      "title_en": "",
      "summary_ko": "\"美 석유기업 공격하겠다\"…이란, 전례 없는 '민간 타깃' 위협 연합인포맥스. 중동 및 동유럽 지정학적 긴장 고조에 따른 국제 유가·원자재 공급망 충격과 인플레이션 재점화 가능성에 유의할 필요가 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE8zRHZPNm1pc0FwMXNhbVN3UkowUV96MUxUaFB4QmFPX0Q5WjRlRm5qTnhaQ1g0ZVVYWGlZdHlpbjF0ZzhkRjlFcWtLSW85T1I0SWJYNndzVXB2ZzU2VEdVT1lub29NS2NWajQwdDJTUmM?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE8zRHZPNm1pc0FwMXNhbVN3UkowUV96MUxUaFB4QmFPX0Q5WjRlRm5qTnhaQ1g0ZVVYWGlZdHlpbjF0ZzhkRjlFcWtLSW85T1I0SWJYNndzVXB2ZzU2VEdVT1lub29NS2NWajQwdDJTUmM?oc=5",
      "category": "us_economy",
      "section_no": 3,
      "section_title": "미국 경제 관련 주요 뉴스 요약",
      "section_icon": "🇺🇸",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Mon, 24 Aug 2026 04:54:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "삼전닉스가 주주환원 위해 1천억弗 환전?…정부 \"보유 원화 많아 달러 매도 제한적\"",
      "title_en": "",
      "summary_ko": "삼전닉스가 주주환원 위해 1천억弗 환전?…정부 \"보유 원화 많아 달러 매도 제한적\" 연합인포맥스. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5IWlFHZHdOUTkyeVF0T2Z4bUVYNG5Ia202VFNlZFFreFlBQ3dNSllRZDFXNjV5M3RHdUZYNVhlVnAyakhaSHNLV1BRYmRURmRMb3E4eUQ3X3NBcHdzWkFSME03b05JY2o0THg1SXhab2jSAXRBVV95cUxQU0dUYzV5UldEWVNOdEVIMHphdGd1d0ZISWpEZS1iQ01tVEFZTHdzNHlLNVgzdUNwSWY5MkRjb0ZfT21PaDU4MXAyYXdkNS1aOU9mWTJmR3BaUnBEMTQtLUZ3NFVuMVBwaXpiSUpHdktFYVRTZQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5IWlFHZHdOUTkyeVF0T2Z4bUVYNG5Ia202VFNlZFFreFlBQ3dNSllRZDFXNjV5M3RHdUZYNVhlVnAyakhaSHNLV1BRYmRURmRMb3E4eUQ3X3NBcHdzWkFSME03b05JY2o0THg1SXhab2jSAXRBVV95cUxQU0dUYzV5UldEWVNOdEVIMHphdGd1d0ZISWpEZS1iQ01tVEFZTHdzNHlLNVgzdUNwSWY5MkRjb0ZfT21PaDU4MXAyYXdkNS1aOU9mWTJmR3BaUnBEMTQtLUZ3NFVuMVBwaXpiSUpHdktFYVRTZQ?oc=5",
      "category": "foreign_flows_korea",
      "section_no": 4,
      "section_title": "한국 외국인 투자자 수급 및 국내 증시 영향",
      "section_icon": "🇰🇷",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 08:02:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "코스피, 3.12% 하락한 6,696.96 마감",
      "title_en": "",
      "summary_ko": "코스피, 3.12% 하락한 6,696.96 마감 연합인포맥스. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 연합인포맥스뿐만 아니라 연합인포맥스 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBtLTZ0UVdGcWFkYVZyWkdwRThweWJmVEp0Y1Z1NFp2WVlkRno2dlNUOGlVeWJwdlRqSGduMl9YTXJBREgxWTNReEh4dVVQUlhHU2VtclkzWXpxU3ZUMTl2UzB0QlNOUzhQTTJfZ1RMcDlMVkht0gF0QVVfeXFMUG0tNnRRV0ZxYWRhVnJaR3BFOHB5YmZUSnRjVnU0WnZZWWRGejZ2U1Q4aVV5YnB2VGpIZ24yX1hNckFESDFZM1F4SHh1VVBSWEdTZW1yWTNZenFTdlQxOXZTMHRCU05TOFBNMl9nVExwOUxWSG0?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBtLTZ0UVdGcWFkYVZyWkdwRThweWJmVEp0Y1Z1NFp2WVlkRno2dlNUOGlVeWJwdlRqSGduMl9YTXJBREgxWTNReEh4dVVQUlhHU2VtclkzWXpxU3ZUMTl2UzB0QlNOUzhQTTJfZ1RMcDlMVkht0gF0QVVfeXFMUG0tNnRRV0ZxYWRhVnJaR3BFOHB5YmZUSnRjVnU0WnZZWWRGejZ2U1Q4aVV5YnB2VGpIZ24yX1hNckFESDFZM1F4SHh1VVBSWEdTZW1yWTNZenFTdlQxOXZTMHRCU05TOFBNMl9nVExwOUxWSG0?oc=5",
      "category": "foreign_flows_korea",
      "section_no": 4,
      "section_title": "한국 외국인 투자자 수급 및 국내 증시 영향",
      "section_icon": "🇰🇷",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 06:39:59 GMT",
      "related_articles": [
        {
          "source": "연합인포맥스",
          "title_ko": "코스피, 0.46% 내린 6,881.07 출발",
          "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1ycHlPTHVYc1lJenpYaGZWb1pxUXAtMGZrejVBRllFMkY5M2V6dGY4dUZLMklUNEhtQWQ2eTZHell5YVZEc0JZZTAxTlR5YVBKTi1QbjdwTUFkZlhaMThoMnpwem9nVnpSQzM5NFNhdGdwZGVB0gF0QVVfeXFMTXJweU9MdVhzWUl6elhoZlZvWnFRcC0wZmt6NUFGWUUyRjkzZXp0Zjh1RksySVQ0SG1BZDZ5Nkd6WXlhVkRzQlllMDFOVHlhUEpOLVBuN3BNQWRmWFoxOGgyenB6b2dWelJDMzk0U2F0Z3BkZUE?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE1ycHlPTHVYc1lJenpYaGZWb1pxUXAtMGZrejVBRllFMkY5M2V6dGY4dUZLMklUNEhtQWQ2eTZHell5YVZEc0JZZTAxTlR5YVBKTi1QbjdwTUFkZlhaMThoMnpwem9nVnpSQzM5NFNhdGdwZGVB0gF0QVVfeXFMTXJweU9MdVhzWUl6elhoZlZvWnFRcC0wZmt6NUFGWUUyRjkzZXp0Zjh1RksySVQ0SG1BZDZ5Nkd6WXlhVkRzQlllMDFOVHlhUEpOLVBuN3BNQWRmWFoxOGgyenB6b2dWelJDMzk0U2F0Z3BkZUE?oc=5"
        }
      ],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "[원화강세 희비] 환율 1,300원 복귀에 철강업계 재무상황 단단해진다",
      "title_en": "",
      "summary_ko": "[원화강세 희비] 환율 1,300원 복귀에 철강업계 재무상황 단단해진다 연합인포맥스. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9wdlUwSlpaUnNBT1hDUVZtYkRoOVVwSU4zYjE3RHNsNFV5bTd1OVYzaEdjQ3A4V2N2UDM2Y1JDSGFnTFN5aDFpS1lGSDBER3czMVVYaVVIWjdHVmxBTDN0aVBEQVFxUk5fNEg1QTFFTVM?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9wdlUwSlpaUnNBT1hDUVZtYkRoOVVwSU4zYjE3RHNsNFV5bTd1OVYzaEdjQ3A4V2N2UDM2Y1JDSGFnTFN5aDFpS1lGSDBER3czMVVYaVVIWjdHVmxBTDN0aVBEQVFxUk5fNEg1QTFFTVM?oc=5",
      "category": "foreign_flows_korea",
      "section_no": 4,
      "section_title": "한국 외국인 투자자 수급 및 국내 증시 영향",
      "section_icon": "🇰🇷",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 00:48:15 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "[다시쓰는 잠재성장률②] 환율 영향은…'低성장 디스카운트' 완화되나 |",
      "title_en": "",
      "summary_ko": "[다시쓰는 잠재성장률②] 환율 영향은…'低성장 디스카운트' 완화되나 | 연합인포맥스. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBHVkhwZ1JvTGltODU1RHVxNFNYRy1WTkdwZWN2aTJ3cWNmMldGQVQ4WmVqM28teUFJVFlqaTNvdk5leXc0RkRtRS00aS1OTTZJR1k4M0wxQnVTaHpiakhwbEdLWklkRFBVWVZseW1hLThBUkRU?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBHVkhwZ1JvTGltODU1RHVxNFNYRy1WTkdwZWN2aTJ3cWNmMldGQVQ4WmVqM28teUFJVFlqaTNvdk5leXc0RkRtRS00aS1OTTZJR1k4M0wxQnVTaHpiakhwbEdLWklkRFBVWVZseW1hLThBUkRU?oc=5",
      "category": "foreign_flows_korea",
      "section_no": 4,
      "section_title": "한국 외국인 투자자 수급 및 국내 증시 영향",
      "section_icon": "🇰🇷",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 06:15:45 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "한국경제",
      "title_ko": "[속보] 원/달러 환율 1,370원대로 하락",
      "title_en": "",
      "summary_ko": "[속보] 원/달러 환율 1,370원대로 하락 한국경제. 외국인 투자자의 국내 증시(코스피/반도체 대형주) 순매수 유입 및 원/달러 환율 1년·3년 평균선 회복 여부를 가늠하는 핵심 대외 지표입니다. 한국경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1lX3FzWUR1ZTZCS2NHdkI3ZFczTHVSOXZxbGxqWmlJbFNPR0xuSmNOVENVcEJIcFFNZi1yc09YTlFWcThEZ2tMMzVaR0VQc0RTMkdBRGo4ZjN4Zw?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1lX3FzWUR1ZTZCS2NHdkI3ZFczTHVSOXZxbGxqWmlJbFNPR0xuSmNOVENVcEJIcFFNZi1yc09YTlFWcThEZ2tMMzVaR0VQc0RTMkdBRGo4ZjN4Zw?oc=5",
      "category": "foreign_flows_korea",
      "section_no": 4,
      "section_title": "한국 외국인 투자자 수급 및 국내 증시 영향",
      "section_icon": "🇰🇷",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 02:16:34 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:32"
    },
    {
      "source": "bok.or.kr",
      "title_ko": "[제2026-14호] Economic Shocks and Income Polarization under Quasi-Marketization: Evidence from North Korea",
      "title_en": "",
      "summary_ko": "[제2026-14호] Economic Shocks and Income Polarization under Quasi-Marketization: Evidence from North Korea bok.or.kr. 한국은행의 금리 결정 및 국내 수출입 펀더멘털, 가계부채와 부동산 경기에 미치는 파급 효과를 주목할 필요가 있습니다. bok.or.kr에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxOWDh0U2gySFNzNUt0X3lwWjhzTTVNei13V050S3kyRGJPOXB3Tmc1X01GWFFfOE1VRHk3RWItNnFjaDBaQkZRY3R5OWZaVlFvWVpCZWdPbXRTYV9jcU1IY2NrbjRhNXNWczdPY2dEMmt6ZU1jYktqZ0FTLXJsdkY2RnJxbXVDZHJselZJSERZaDB6TXJTVElWQlVoX0RZSVNjMFZJZ3pWbzhFcjdiWV93OHUzTHZydG91T3I5N0t3?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxOWDh0U2gySFNzNUt0X3lwWjhzTTVNei13V050S3kyRGJPOXB3Tmc1X01GWFFfOE1VRHk3RWItNnFjaDBaQkZRY3R5OWZaVlFvWVpCZWdPbXRTYV9jcU1IY2NrbjRhNXNWczdPY2dEMmt6ZU1jYktqZ0FTLXJsdkY2RnJxbXVDZHJselZJSERZaDB6TXJTVElWQlVoX0RZSVNjMFZJZ3pWbzhFcjdiWV93OHUzTHZydG91T3I5N0t3?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 30,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 03:32:03 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "정점식 \"당정협의 생색내기 쇼…부동산 정책이 김민석 취임 선물인가\" |",
      "title_en": "",
      "summary_ko": "정점식 \"당정협의 생색내기 쇼…부동산 정책이 김민석 취임 선물인가\" | 연합인포맥스. 한국은행의 금리 결정 및 국내 수출입 펀더멘털, 가계부채와 부동산 경기에 미치는 파급 효과를 주목할 필요가 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBZcG1DZlpvV0RGMGl3TW5sZEJva1o0YUUzWkxhLWtHR3NNeDJqWDhiLV9fOWhqMEZseDRHbzVSQXVab0R3ZHMwNTZhUXhiTS15ZnRocWNHSVp6dWE5TVBiOG9RLW5TOU41ZldyVEpJXzhYMTZ4?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTFBZcG1DZlpvV0RGMGl3TW5sZEJva1o0YUUzWkxhLWtHR3NNeDJqWDhiLV9fOWhqMEZseDRHbzVSQXVab0R3ZHMwNTZhUXhiTS15ZnRocWNHSVp6dWE5TVBiOG9RLW5TOU41ZldyVEpJXzhYMTZ4?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Mon, 24 Aug 2026 01:12:22 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "[이번주 한국은행 및 금융위·금감원 일정]",
      "title_en": "",
      "summary_ko": "[이번주 한국은행 및 금융위·금감원 일정] 연합인포맥스. 한국은행의 금리 결정 및 국내 수출입 펀더멘털, 가계부채와 부동산 경기에 미치는 파급 효과를 주목할 필요가 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE9wY2lUNWJiX0xnX21CcEZ5cFR4cXcxV1RZaTdmRkRtUmhLRzdtQ2pCUEVzeEUxRW9EZTg0TS10NVpKR0l1QXFaQk1JOHRYUmZvdHk4ZU15U0hnODJFOExEYjlrY21ISlNSR1NJeHFMQkZxMHVq0gF0QVVfeXFMT3BjaVQ1YmJfTGdfbUJwRnlwVHhxdzFXVFlpN2ZGRG1SaEtHN21DakJQRXN4RTFFb0RlODRNLXQ1WkpHSXVBcVpCTUk4dFhSZm90eThlTXlTSGc4MkU4TERiOWtjbUhKU1JHU0l4cUxCRnEwdWo?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMidEFVX3lxTE9wY2lUNWJiX0xnX21CcEZ5cFR4cXcxV1RZaTdmRkRtUmhLRzdtQ2pCUEVzeEUxRW9EZTg0TS10NVpKR0l1QXFaQk1JOHRYUmZvdHk4ZU15U0hnODJFOExEYjlrY21ISlNSR1NJeHFMQkZxMHVq0gF0QVVfeXFMT3BjaVQ1YmJfTGdfbUJwRnlwVHhxdzFXVFlpN2ZGRG1SaEtHN21DakJQRXN4RTFFb0RlODRNLXQ1WkpHSXVBcVpCTUk4dFhSZm90eThlTXlTSGc4MkU4TERiOWtjbUhKU1JHU0l4cUxCRnEwdWo?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Sun, 23 Aug 2026 22:04:13 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "[뉴욕증시-주간전망] '베선트 풋'에 곤란해진 워시…엔비디아 실적·PCE 지표도",
      "title_en": "",
      "summary_ko": "[뉴욕증시-주간전망] '베선트 풋'에 곤란해진 워시…엔비디아 실적·PCE 지표도 연합인포맥스. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5kUERwbFBWbUozTDV4WEYwLUd1MzhQY2FSYlhMdGVtWjAzMDhpRmRueDBJbzZYZmVfQnM2SVNjM3JydER3WWNaMnhWMEpBUGs3SWVCYVpoYWc1YVVJUnEtVDUzdkxmQmVYTXluZy1QWHM?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5kUERwbFBWbUozTDV4WEYwLUd1MzhQY2FSYlhMdGVtWjAzMDhpRmRueDBJbzZYZmVfQnM2SVNjM3JydER3WWNaMnhWMEpBUGs3SWVCYVpoYWc1YVVJUnEtVDUzdkxmQmVYTXluZy1QWHM?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sat, 22 Aug 2026 22:00:25 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "삼성 110조·하이닉스 40조+α…'금액보다 환원율' 따져보니",
      "title_en": "",
      "summary_ko": "삼성 110조·하이닉스 40조+α…'금액보다 환원율' 따져보니 연합인포맥스. 미 재무부의 TGA 현금 잔고 방출과 40조 달러 국가부채 조달(QRA) 사이클에 따른 국채 기간 프리미엄 및 글로벌 달러 유동성 환경에 직접적인 영향을 미칠 수 있습니다. 연합인포맥스뿐만 아니라 한국경제 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBpczMxLWstS2JkRVlsX3M4YVdXdWlMcTJaRUJMZVI4YTJJWmlpRFhXZFg5N1REbmRMRjVKYXhuRGV1T3gtZ2x6dU03dXBaYUV6aTVCeWg4S1lBWEhPUktNT0t5YnNSNklxSDlweVBEQzI?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBpczMxLWstS2JkRVlsX3M4YVdXdWlMcTJaRUJMZVI4YTJJWmlpRFhXZFg5N1REbmRMRjVKYXhuRGV1T3gtZ2x6dU03dXBaYUV6aTVCeWg4S1lBWEhPUktNT0t5YnNSNklxSDlweVBEQzI?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sat, 22 Aug 2026 22:00:00 GMT",
      "related_articles": [
        {
          "source": "한국경제",
          "title_ko": "삼성전자, 30조 특별배당 이어 40조 더 풀듯",
          "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE81Qkd0bXlWck1WaWlPTjRIUmJDbXFTXzlMVjhRVmlSR0lSb1ZsZUpSalMzM0puRkluc2RMazl2QWY5OEhFSDI2MUcyLWpnSUhqMmV0QTFpcFVndw?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE81Qkd0bXlWck1WaWlPTjRIUmJDbXFTXzlMVjhRVmlSR0lSb1ZsZUpSalMzM0puRkluc2RMazl2QWY5OEhFSDI2MUcyLWpnSUhqMmV0QTFpcFVndw?oc=5"
        }
      ],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "코스피 8천선 회복 가늠자…잭슨홀·엔비디아가 온다",
      "title_en": "",
      "summary_ko": "코스피 8천선 회복 가늠자…잭슨홀·엔비디아가 온다 연합인포맥스. 빅테크 AI 데이터센터 확장 사이클과 HBM 반도체 수요, 그리고 전력망·변압기·구리 등 핵심 인프라 및 원자재 공급 병목 현상과 밀접하게 연계된 이슈입니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBDY3FFMXhPYjNjV2VackVXUl9vQVlqR3FidTlIRTZtdXoxRWVFeEcxTU5vaG1iaE90SE9rYVFJTXJpaFJDY3V4WUl6dEY1TEExZ2o3VTB1Umt0WkVjcXlLaEFVdldFSFA3bjZFbDJXTU4?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBDY3FFMXhPYjNjV2VackVXUl9vQVlqR3FidTlIRTZtdXoxRWVFeEcxTU5vaG1iaE90SE9rYVFJTXJpaFJDY3V4WUl6dEY1TEExZ2o3VTB1Umt0WkVjcXlLaEFVdldFSFA3bjZFbDJXTU4?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sun, 23 Aug 2026 23:16:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "한국경제",
      "title_ko": "'슈퍼 乙' 삼전닉스 웃었다…발목 잡힌 엔비디아 결국 '백기'",
      "title_en": "",
      "summary_ko": "'슈퍼 乙' 삼전닉스 웃었다…발목 잡힌 엔비디아 결국 '백기' 한국경제. 빅테크 AI 데이터센터 확장 사이클과 HBM 반도체 수요, 그리고 전력망·변압기·구리 등 핵심 인프라 및 원자재 공급 병목 현상과 밀접하게 연계된 이슈입니다. 한국경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5lZm43Y3A4allOWUllb2EwcnM3ODNkM2MzS3RwaEhzUUNPTGRXeFdjLUdpZHNjMHVSaFNUSmNuOXJ4MkFuQWxqbHpMbmh4OE1WcDZBVERHQl92QQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5lZm43Y3A4allOWUllb2EwcnM3ODNkM2MzS3RwaEhzUUNPTGRXeFdjLUdpZHNjMHVSaFNUSmNuOXJ4MkFuQWxqbHpMbmh4OE1WcDZBVERHQl92QQ?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sun, 23 Aug 2026 08:45:04 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    },
    {
      "source": "한국경제",
      "title_ko": "GPU 대신 연산까지 수행…삼성 '차세대 HBM' 공개",
      "title_en": "",
      "summary_ko": "GPU 대신 연산까지 수행…삼성 '차세대 HBM' 공개 한국경제. 빅테크 AI 데이터센터 확장 사이클과 HBM 반도체 수요, 그리고 전력망·변압기·구리 등 핵심 인프라 및 원자재 공급 병목 현상과 밀접하게 연계된 이슈입니다. 한국경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9YMlN1X09qeVQ2NS1QUVEwX01pcThFdlh2WGhucjVZQUZBMklIdml3RTNaU201VEZBZHZvbzlhVmJ5cHE4Y3BPckd0UjBaUDNvRy1iTm53bTNzUQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9YMlN1X09qeVQ2NS1QUVEwX01pcThFdlh2WGhucjVZQUZBMklIdml3RTNaU201VEZBZHZvbzlhVmJ5cHE4Y3BPckd0UjBaUDNvRy1iTm53bTNzUQ?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Mon, 24 Aug 2026 08:47:42 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-24 21:55:33"
    }
  ]
};
window.__KEYWORDS_CONFIG__ = {
  "score_threshold": 20,
  "swell_keywords": [
    "tga",
    "재무부 일반계정",
    "현금 잔고",
    "스콧 베센트",
    "베센트",
    "40조",
    "40 trillion",
    "국가부채",
    "national debt",
    "부채 한도",
    "debt ceiling",
    "스테이블코인",
    "stablecoin",
    "테더",
    "서클",
    "단기국채",
    "t-bills",
    "hbm",
    "엔비디아",
    "nvidia",
    "tsmc",
    "딥시크",
    "deepseek",
    "전력망",
    "power grid",
    "변압기",
    "transformer",
    "smr",
    "원전",
    "구리",
    "copper",
    "닥터 코퍼",
    "전력",
    "전력난",
    "전력 부족",
    "power shortage",
    "electricity",
    "희토류",
    "히토류",
    "rare earth",
    "rare earths",
    "핵심광물",
    "critical minerals",
    "그린란드",
    "greenland",
    "1500원",
    "1600원",
    "패권",
    "이란",
    "iran",
    "호르무즈",
    "hormuz",
    "strait of hormuz",
    "중동",
    "middle east",
    "우크라이나",
    "ukraine",
    "러시아 우크라이나",
    "russia ukraine",
    "지정학"
  ],
  "impact_keywords": [
    "fomc",
    "금리 결정",
    "금리 인하",
    "금리 인상",
    "rate cut",
    "rate hike",
    "파월",
    "powell",
    "긴급",
    "shock",
    "쇼크",
    "surprise",
    "서프라이즈",
    "사상 최대",
    "record high",
    "경고",
    "warning",
    "폭등",
    "폭락",
    "crash",
    "surge",
    "순매도",
    "순매수",
    "외국인"
  ]
};
window.__SOURCES_CONFIG__ = [
  {
    "id": "fed_official",
    "name": "🏛️ 미국 연방준비제도 (Federal Reserve)",
    "website": "https://www.federalreserve.gov",
    "domain": "federalreserve.gov",
    "description": "연준 공식 성명서, 통화정책 결정문, 파월 의장 연설문 및 베이지북",
    "enabled": true
  },
  {
    "id": "ny_fed",
    "name": "📑 뉴욕 연방준비은행 (NY Fed Liberty Street)",
    "website": "https://libertystreeteconomics.newyorkfed.org",
    "domain": "libertystreeteconomics.newyorkfed.org",
    "description": "뉴욕 연은 유동성, 재정적자, 국채 시장 심층 연구 리포트",
    "enabled": true
  },
  {
    "id": "bloomberg",
    "name": "🌐 Bloomberg (블룸버그)",
    "website": "https://www.bloomberg.com",
    "domain": "bloomberg.com",
    "description": "글로벌 1티어 경제 매체 (거시경제, 연준 금리, 채권, 원자재, 빅테크)",
    "enabled": true
  },
  {
    "id": "reuters",
    "name": "🌐 Reuters (로이터 통신)",
    "website": "https://www.reuters.com",
    "domain": "reuters.com",
    "description": "글로벌 통화정책, 중앙은행 금리 결정, 지정학 긴급 속보",
    "enabled": true
  },
  {
    "id": "wsj",
    "name": "🇺🇸 Wall Street Journal (월스트리트저널)",
    "website": "https://www.wsj.com",
    "domain": "wsj.com",
    "description": "미국 실물 경제, 40조 달러 국가부채, 재무부 국채 발행(QRA), 기업 동향",
    "enabled": true
  },
  {
    "id": "cnbc",
    "name": "📺 CNBC (미국 CNBC)",
    "website": "https://www.cnbc.com",
    "domain": "cnbc.com",
    "description": "미국 금융시장 실시간 거시, 채권수익률, 환율, 고용/소비자물가(CPI)",
    "enabled": true
  },
  {
    "id": "ft",
    "name": "🇬🇧 Financial Times (파이낸셜타임스)",
    "website": "https://www.ft.com",
    "domain": "ft.com",
    "description": "영국/유럽 및 글로벌 매크로 경제, 국제 금융시장 심층 분석",
    "enabled": true
  },
  {
    "id": "economist",
    "name": "🇬🇧 The Economist (이코노미스트)",
    "website": "https://www.economist.com",
    "domain": "economist.com",
    "description": "글로벌 매크로 메가트렌드, 지정학 구조 분석 및 경제 전망",
    "enabled": true
  },
  {
    "id": "nytimes_biz",
    "name": "📰 New York Times Business (뉴욕타임스)",
    "website": "https://www.nytimes.com/section/business",
    "domain": "nytimes.com",
    "description": "미국 경제정책, 무역 갈등, 테크 산업 규제 및 거시 트렌드",
    "enabled": true
  },
  {
    "id": "ecb",
    "name": "🇪🇺 ECB (유럽중앙은행)",
    "website": "https://www.ecb.europa.eu",
    "domain": "ecb.europa.eu",
    "description": "유로존 기준금리 결정, 유럽 물가 및 통화정책 공식 발표",
    "enabled": true
  },
  {
    "id": "boj",
    "name": "🇯🇵 BOJ (일본은행)",
    "website": "https://www.boj.or.jp",
    "domain": "boj.or.jp",
    "description": "일본은행 금리 결정, 엔화 정책, 엔캐리 트레이드 관련 공식 발표",
    "enabled": true
  },
  {
    "id": "nikkei",
    "name": "🇯🇵 Nikkei Asia (닛케이 아시아)",
    "website": "https://asia.nikkei.com",
    "domain": "asia.nikkei.com",
    "description": "아시아 경제, 글로벌 반도체/HBM 공급망, 아시아 환율 동향",
    "enabled": true
  },
  {
    "id": "caixin",
    "name": "🇨🇳 Caixin Global (중국 차이신)",
    "website": "https://www.caixinglobal.com",
    "domain": "caixinglobal.com",
    "description": "중국 실물 경제지표, 부동산 부채, 통화정책 및 금융시장 전문",
    "enabled": true
  },
  {
    "id": "scmp",
    "name": "🇨🇳 SCMP (사우스차이나모닝포스트)",
    "website": "https://www.scmp.com",
    "domain": "scmp.com",
    "description": "중국 거시경제, 미중 기술/원자재 패권 갈등, 위안화 환율",
    "enabled": true
  },
  {
    "id": "goldman_sachs",
    "name": "📊 Goldman Sachs Research (골드만삭스)",
    "website": "https://www.goldmansachs.com/insights",
    "domain": "goldmansachs.com",
    "description": "월가 대표 투자은행 글로벌 거시 전망 및 섹터별 인사이트 리포트",
    "enabled": true
  },
  {
    "id": "imf",
    "name": "🌐 IMF (국제통화기금)",
    "website": "https://www.imf.org",
    "domain": "imf.org",
    "description": "글로벌 금융안정 보고서(GFSR), 세계 경제성장률 전망(WEO)",
    "enabled": true
  },
  {
    "id": "bis",
    "name": "🌐 BIS (국제결제은행)",
    "website": "https://www.bis.org",
    "domain": "bis.org",
    "description": "중앙은행들의 중앙은행, 글로벌 잉여 유동성 및 은행 건전성 분석",
    "enabled": true
  },
  {
    "id": "bok",
    "name": "🏛️ 한국은행 (Bank of Korea)",
    "website": "https://www.bok.or.kr",
    "domain": "bok.or.kr",
    "description": "금융통화위원회 기준금리 결정, 국내 경제전망 및 통화신용정책 보고서",
    "enabled": true
  },
  {
    "id": "einfomax",
    "name": "🇰🇷 연합인포맥스",
    "website": "https://news.einfomax.co.kr",
    "domain": "einfomax.co.kr",
    "description": "외환(달러/원), 채권 금리, 외국인 순매수/선물 수급 실시간 전문",
    "enabled": true
  },
  {
    "id": "hankyung",
    "name": "🇰🇷 한국경제신문 (한경)",
    "website": "https://www.hankyung.com",
    "domain": "hankyung.com",
    "description": "국내외 증시, 반도체/수출입, 거시경제 및 부동산/가계부채 동향",
    "enabled": true
  },
  {
    "id": "mk",
    "name": "🇰🇷 매일경제신문 (매경)",
    "website": "https://www.mk.co.kr",
    "domain": "mk.co.kr",
    "description": "국내외 거시경제, 외환 및 증시, 기업 투자 사이클 심층 보도",
    "enabled": true
  },
  {
    "id": "yna",
    "name": "🇰🇷 연합뉴스 (경제/금융)",
    "website": "https://www.yna.co.kr",
    "domain": "yna.co.kr",
    "description": "국내 수출입 펀더멘털, 소비자물가(CPI), 정부 경제재정 정책 속보",
    "enabled": true
  },
  {
    "id": "chosunbiz",
    "name": "🇰🇷 조선비즈",
    "website": "https://biz.chosun.com",
    "domain": "chosunbiz.com",
    "description": "국내외 거시경제, IT/반도체 산업, 금융 및 글로벌 공급망",
    "enabled": true
  },
  {
    "id": "the_information",
    "name": "🤖 The Information / Tech (실리콘밸리 테크)",
    "website": "https://www.theinformation.com",
    "domain": "theinformation.com",
    "description": "글로벌 AI 빅테크, AI 칩(GPU/HBM), 데이터센터 전력 인프라 특종 보도",
    "enabled": true
  }
];
