window.__BRIEFING_DATA__ = {
  "metadata": {
    "title": "글로벌 매크로 & 경제 모닝 브리핑",
    "updated_at": "2026-08-26 21:54:48",
    "date_str": "2026년 08월 26일 (수)",
    "indicator_count": 19,
    "news_count": 12
  },
  "indicators": [
    {
      "id": "us_short",
      "symbol": "^IRX",
      "name_ko": "미국 단기 국채 금리 (13주)",
      "name_en": "US 13W T-Bill",
      "group": "macro",
      "unit": "%",
      "format": "{:.3f}%",
      "description": "단기 무위험 금리 및 연준의 기준금리 방향성을 가장 빠르게 선반영하는 단기채 지표",
      "price": 3.695,
      "previous_close": 3.705,
      "change": -0.01,
      "change_percent": -0.27,
      "display_price": "3.695%",
      "status": "down",
      "history": [
        3.705,
        3.7,
        3.703,
        3.71,
        3.703,
        3.705,
        3.695
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EIRX/",
      "updated_at": "2026-08-26 21:54:21"
    },
    {
      "id": "us10y",
      "symbol": "^TNX",
      "name_ko": "미국 10년물 국채 금리",
      "name_en": "US 10Y Yield",
      "group": "macro",
      "unit": "%",
      "has_yield_signal": true,
      "format": "{:.3f}%",
      "description": "글로벌 무위험 금리 벤치마크, 밸류에이션 및 유동성 바로미터 (5% 돌파 시 경계 경보)",
      "price": 4.649,
      "previous_close": 4.706,
      "change": -0.057,
      "change_percent": -1.21,
      "display_price": "4.649%",
      "status": "down",
      "history": [
        4.706,
        4.653,
        4.696,
        4.738,
        4.704,
        4.639,
        4.649
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ETNX/",
      "updated_at": "2026-08-26 21:54:22",
      "yield_signal": {
        "level": "warn",
        "tag": "🟠 주의 구간 (4.50~5.00%)",
        "desc": "주식 밸류에이션 부담 & 환율 상승 압력"
      }
    },
    {
      "id": "us30y",
      "symbol": "^TYX",
      "name_ko": "미국 30년물 국채 금리",
      "name_en": "US 30Y Yield",
      "group": "macro",
      "unit": "%",
      "format": "{:.3f}%",
      "description": "초장기 채권 금리, 미국의 막대한 재정적자 및 기간 프리미엄(Term Premium) 바로미터",
      "price": 5.178,
      "previous_close": 5.285,
      "change": -0.107,
      "change_percent": -2.02,
      "display_price": "5.178%",
      "status": "down",
      "history": [
        5.285,
        5.194,
        5.237,
        5.276,
        5.231,
        5.174,
        5.178
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ETYX/",
      "updated_at": "2026-08-26 21:54:22"
    },
    {
      "id": "dxy",
      "symbol": "DX-Y.NYB",
      "name_ko": "달러 인덱스 (DXY)",
      "name_en": "US Dollar Index",
      "group": "macro",
      "unit": "pt",
      "format": "{:.2f} pt",
      "description": "주요 6개국 통화 대비 달러화 가치 (달러 강세/약세 지표)",
      "price": 99.021,
      "previous_close": 98.83,
      "change": 0.191,
      "change_percent": 0.19,
      "display_price": "99.02 pt",
      "status": "up",
      "history": [
        98.83,
        98.9,
        98.8,
        99.0,
        98.92,
        99.021
      ],
      "chart_url": "https://finance.yahoo.com/quote/DX-Y.NYB/",
      "updated_at": "2026-08-26 21:54:23"
    },
    {
      "id": "usdjpy",
      "symbol": "JPY=X",
      "name_ko": "달러 / 엔 환율 (USD/JPY)",
      "name_en": "USD / JPY",
      "group": "macro",
      "unit": "엔",
      "format": "{:,.2f}엔",
      "description": "엔 캐리 트레이드 청산 리스크 및 일본은행(BOJ) 통화정책 바로미터",
      "price": 159.205,
      "previous_close": 159.34,
      "change": -0.135,
      "change_percent": -0.08,
      "display_price": "159.21엔",
      "status": "down",
      "history": [
        159.34,
        159.55,
        158.276,
        158.883,
        158.904,
        159.139,
        159.205
      ],
      "chart_url": "https://finance.yahoo.com/quote/JPY%3DX/",
      "updated_at": "2026-08-26 21:54:24"
    },
    {
      "id": "gold",
      "symbol": "GC=F",
      "name_ko": "국제 금 시세 (선물)",
      "name_en": "Gold Futures",
      "group": "macro",
      "unit": "$",
      "format": "${:,.2f}",
      "description": "인플레이션 헤지 및 대표 닻(Anchor) 안전자산, 실질금리 역방향 흐름",
      "price": 4679.4,
      "previous_close": 4489.4,
      "change": 190.0,
      "change_percent": 4.23,
      "display_price": "$4,679.40",
      "status": "up",
      "history": [
        4489.4,
        4516.3,
        4624.1,
        4640.8,
        4638.1,
        4679.4
      ],
      "chart_url": "https://finance.yahoo.com/quote/GC%3DF/",
      "updated_at": "2026-08-26 21:54:24"
    },
    {
      "id": "wti",
      "symbol": "CL=F",
      "name_ko": "국제 유가 (WTI 원유)",
      "name_en": "WTI Crude Oil",
      "group": "macro",
      "unit": "$",
      "format": "${:.2f}",
      "description": "헤드라인 인플레이션 시한폭탄 및 원자재 물가 압력 지표",
      "price": 80.26,
      "previous_close": 85.83,
      "change": -5.57,
      "change_percent": -6.49,
      "display_price": "$80.26",
      "status": "down",
      "history": [
        85.83,
        87.83,
        87.06,
        85.01,
        82.36,
        80.26
      ],
      "chart_url": "https://finance.yahoo.com/quote/CL%3DF/",
      "updated_at": "2026-08-26 21:54:25"
    },
    {
      "id": "btc",
      "symbol": "BTC-USD",
      "name_ko": "비트코인 (BTC)",
      "name_en": "Bitcoin",
      "group": "macro",
      "unit": "$",
      "format": "${:,.0f}",
      "description": "글로벌 위험자산 선호도 및 잉여 유동성 측정 지표",
      "price": 78309.83,
      "previous_close": 73032.76,
      "change": 5277.07,
      "change_percent": 7.23,
      "display_price": "$78,310",
      "status": "up",
      "history": [
        73032.758,
        78335.188,
        77083.414,
        77755.266,
        78964.484,
        78564.977,
        78309.828
      ],
      "chart_url": "https://finance.yahoo.com/quote/BTC-USD/",
      "updated_at": "2026-08-26 21:54:25"
    },
    {
      "id": "tga",
      "symbol": "TGA Balance",
      "name_ko": "미 재무부 TGA 현금 잔고",
      "name_en": "US Treasury General Account",
      "group": "macro",
      "unit": "$",
      "is_tga": true,
      "format": "${:,.1f}B",
      "description": "스콧 베센트 재무장관의 유동성 탄약고 (잔고 방출=유동성 공급/주가상승, 충전=유동성 흡수)",
      "price": 933.2,
      "previous_close": 50.4,
      "change": 882.8,
      "change_percent": 0.0,
      "display_price": "$933.2B (약 9,332억$)",
      "status": "up",
      "history": [
        17.6,
        15.8,
        935.1,
        966.8,
        16.8,
        50.4,
        933.2
      ],
      "chart_url": "https://fiscaldata.treasury.gov/datasets/daily-treasury-statement/operating-cash-balance",
      "updated_at": "2026-08-26 21:54:26"
    },
    {
      "id": "sp500",
      "symbol": "^GSPC",
      "name_ko": "S&P 500 지수",
      "name_en": "S&P 500",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "미국 대형주 대표 벤치마크 및 글로벌 주식 투자 심리",
      "price": 7677.28,
      "previous_close": 7785.76,
      "change": -108.48,
      "change_percent": -1.39,
      "display_price": "7,677.28",
      "status": "down",
      "history": [
        7745.06,
        7691.76,
        7707.98,
        7641.16,
        7674.37,
        7652.86,
        7677.28
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EGSPC/",
      "updated_at": "2026-08-26 21:54:28"
    },
    {
      "id": "nasdaq",
      "symbol": "^NDX",
      "name_ko": "나스닥 100 지수",
      "name_en": "Nasdaq 100",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "빅테크 및 성장주 중심의 글로벌 기술주 지표",
      "price": 29209.229,
      "previous_close": 30046.14,
      "change": -836.911,
      "change_percent": -2.79,
      "display_price": "29,209.23",
      "status": "down",
      "history": [
        29995.381,
        29490.961,
        29426.02,
        29213.16,
        29308.859,
        29023.18,
        29209.23
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ENDX/",
      "updated_at": "2026-08-26 21:54:28"
    },
    {
      "id": "sox",
      "symbol": "^SOX",
      "name_ko": "필라델피아 반도체 지수",
      "name_en": "PHLX Semiconductor",
      "group": "us_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "글로벌 AI/반도체 밸류체인 및 삼성전자/SK하이닉스 외국인 수급 직결",
      "price": 11588.038,
      "previous_close": 12417.05,
      "change": -829.012,
      "change_percent": -6.68,
      "display_price": "11,588.04",
      "status": "down",
      "history": [
        12621.0,
        11992.46,
        11738.23,
        11800.02,
        11740.37,
        11423.17,
        11588.04
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5ESOX/",
      "updated_at": "2026-08-26 21:54:29"
    },
    {
      "id": "vix",
      "symbol": "^VIX",
      "name_ko": "VIX 변동성 지수 (공포지수)",
      "name_en": "CBOE Volatility",
      "group": "us_market",
      "unit": "pt",
      "format": "{:.2f}",
      "description": "월가 S&P500 옵션 내재 변동성 및 투자자 공포/탐욕 심리",
      "price": 15.71,
      "previous_close": 15.84,
      "change": -0.13,
      "change_percent": -0.82,
      "display_price": "15.71",
      "status": "down",
      "history": [
        15.84,
        14.89,
        16.01,
        15.13,
        15.85,
        15.45,
        15.71
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EVIX/",
      "updated_at": "2026-08-26 21:54:29"
    },
    {
      "id": "usdkrw",
      "symbol": "KRW=X",
      "name_ko": "달러 / 원 환율",
      "name_en": "USD / KRW",
      "group": "korea_market",
      "unit": "원",
      "has_fx_averages": true,
      "format": "{:,.2f}원",
      "description": "원화 가치 및 외인 수급의 핵심 변수 (1년 평균 및 3년 평균 기준선 제공)",
      "price": 1384.78,
      "previous_close": 1414.73,
      "change": -29.95,
      "change_percent": -2.12,
      "display_price": "1,384.78원",
      "status": "down",
      "history": [
        1414.73,
        1413.58,
        1389.4,
        1390.79,
        1384.98,
        1380.76,
        1384.78
      ],
      "chart_url": "https://finance.yahoo.com/quote/KRW%3DX/",
      "updated_at": "2026-08-26 21:54:30",
      "fx_averages": {
        "avg_1y": 1460.5,
        "avg_3y": 1401.0
      }
    },
    {
      "id": "kospi",
      "symbol": "^KS11",
      "name_ko": "코스피 종합지수 (KOSPI)",
      "name_en": "KOSPI Composite",
      "group": "korea_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "국내 대형주/제조업 중심 유가증권시장 대표 벤치마크",
      "price": 6808.21,
      "previous_close": 6977.94,
      "change": -169.73,
      "change_percent": -2.43,
      "display_price": "6,808.21",
      "status": "down",
      "history": [
        6869.83,
        6471.17,
        6852.58,
        6912.95,
        6696.96,
        6742.74,
        6808.21
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EKS11/",
      "updated_at": "2026-08-26 21:54:31"
    },
    {
      "id": "kosdaq",
      "symbol": "^KQ11",
      "name_ko": "코스닥 종합지수 (KOSDAQ)",
      "name_en": "KOSDAQ Composite",
      "group": "korea_market",
      "unit": "pt",
      "format": "{:,.2f}",
      "description": "국내 IT, 바이오, 2차전지, 중소형 성장주 대표 벤치마크",
      "price": 826.87,
      "previous_close": 864.65,
      "change": -37.78,
      "change_percent": -4.37,
      "display_price": "826.87",
      "status": "down",
      "history": [
        834.2,
        824.46,
        840.89,
        801.94,
        813.33,
        827.15,
        826.87
      ],
      "chart_url": "https://finance.yahoo.com/quote/%5EKQ11/",
      "updated_at": "2026-08-26 21:54:32"
    },
    {
      "id": "kr_bond3y",
      "symbol": "KR-BOND 3Y",
      "name_ko": "한국 국고채 3년물 금리",
      "name_en": "Korea Treasury 3Y",
      "group": "korea_market",
      "unit": "%",
      "is_kr_bond": true,
      "format": "{:.2f}%",
      "description": "국내 채권시장 단기 기준물, 한국은행 통화정책 및 기업 자금조달 금리 벤치마크",
      "price": 3.81,
      "previous_close": 3.83,
      "change": -0.02,
      "change_percent": -0.52,
      "display_price": "3.81%",
      "status": "down",
      "history": [
        3.84,
        3.79,
        3.81,
        3.85,
        3.83,
        3.83,
        3.81
      ],
      "chart_url": "https://finance.naver.com/marketindex/interestDetail.naver?marketindexCd=IRR_GOVT03Y",
      "updated_at": "2026-08-26 21:54:32"
    },
    {
      "id": "kr_bond10y",
      "symbol": "KR-BOND 10Y",
      "name_ko": "한국 국고채 10년물 금리",
      "name_en": "Korea Treasury 10Y",
      "group": "korea_market",
      "unit": "%",
      "is_kr_bond10y": true,
      "has_kr_yield_signal": true,
      "format": "{:.3f}%",
      "description": "국내 장기 무위험 금리 벤치마크 (4.0% 경계 / 4.5% 대피 / 5.0% 위기)",
      "price": 4.285,
      "previous_close": 4.342,
      "change": -0.057,
      "change_percent": -1.31,
      "display_price": "4.285%",
      "status": "down",
      "history": [
        4.4,
        4.38,
        4.35,
        4.33,
        4.31,
        4.29
      ],
      "chart_url": "https://kr.investing.com/rates-bonds/south-korea-10-year-bond-yield",
      "updated_at": "2026-08-26 21:54:33",
      "yield_signal": {
        "level": "warn",
        "tag": "🟡 경계 경보 (4.0~4.5%)",
        "desc": "외환/채권 시장 경계 구간"
      }
    },
    {
      "id": "ewy",
      "symbol": "EWY",
      "name_ko": "MSCI 한국 ETF (EWY)",
      "name_en": "iShares MSCI S.Korea",
      "group": "korea_market",
      "unit": "$",
      "format": "${:.2f}",
      "description": "뉴욕 야간 외국인 한국물 거래 (익일 아침 코스피 시초가 선행 지표)",
      "price": 180.15,
      "previous_close": 179.74,
      "change": 0.41,
      "change_percent": 0.23,
      "display_price": "$180.15",
      "status": "up",
      "history": [
        185.1,
        170.05,
        174.43,
        178.16,
        178.34,
        173.64,
        180.15
      ],
      "chart_url": "https://finance.yahoo.com/quote/EWY/",
      "updated_at": "2026-08-26 21:54:33"
    }
  ],
  "news": [
    {
      "source": "연합인포맥스",
      "title_ko": "BNY멜론 \"TGA 써도 결국 단기채 찍어야…美 장기채 유동성 문제 안보여\"",
      "title_en": "",
      "summary_ko": "BNY멜론 \"TGA 써도 결국 단기채 찍어야…美 장기채 유동성 문제 안보여\" 연합인포맥스. 미 재무부의 TGA 현금 잔고 방출과 40조 달러 국가부채 조달(QRA) 사이클에 따른 국채 기간 프리미엄 및 글로벌 달러 유동성 환경에 직접적인 영향을 미칠 수 있습니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9xYmZhOHVGZVN2Z1FTMXBDV1BjUHJ6RUlVRzdfRkp0UDZxVDlyUlFUNkFPNFl6R3NubVBxZnBWRHI5MGVsMzVocXFGblZ3Uy1LaVU4cm1RYVVXek9jU2ZBSEhFM3I3NXA3RUtORnlhbFY?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9xYmZhOHVGZVN2Z1FTMXBDV1BjUHJ6RUlVRzdfRkp0UDZxVDlyUlFUNkFPNFl6R3NubVBxZnBWRHI5MGVsMzVocXFGblZ3Uy1LaVU4cm1RYVVXek9jU2ZBSEhFM3I3NXA3RUtORnlhbFY?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Wed, 26 Aug 2026 02:04:14 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "한국경제",
      "title_ko": "중동發 인플레 압박에…ECB도 금리인상 속도 높인다",
      "title_en": "",
      "summary_ko": "중동發 인플레 압박에…ECB도 금리인상 속도 높인다 한국경제. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 한국경제뿐만 아니라 미디어파인, Investing.com 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9BVHdhSEJFaXZvSldfMm1FdnRockhTNThoOFdlQktCRFphU3pDSmZvWFc4Z256WTB4VTVyWHY5X0tDZmRNYlBSUW0xYVNBQ1k3YTQ3b3RCQV9zQQ?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9BVHdhSEJFaXZvSldfMm1FdnRockhTNThoOFdlQktCRFphU3pDSmZvWFc4Z256WTB4VTVyWHY5X0tDZmRNYlBSUW0xYVNBQ1k3YTQ3b3RCQV9zQQ?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 50,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Wed, 26 Aug 2026 09:03:01 GMT",
      "related_articles": [
        {
          "source": "Investing.com",
          "title_ko": "콜린스 \"인플레 미둔화 시 연준, 조만간 금리 인상 불가피\"",
          "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5xVTFldjQ2OTM3N1BMUnJkRGpXczJlVjhaVkVzTV9RODhRX1VZVWtCZjJwOS1YTVBFYmZBdG90MGlvZEcxazR3UmlwN1hjT3I5TzZmc0hxWWJScDUyWVJMTFZ2Z3hWWDM0d1BHYTRoQW0?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5xVTFldjQ2OTM3N1BMUnJkRGpXczJlVjhaVkVzTV9RODhRX1VZVWtCZjJwOS1YTVBFYmZBdG90MGlvZEcxazR3UmlwN1hjT3I5TzZmc0hxWWJScDUyWVJMTFZ2Z3hWWDM0d1BHYTRoQW0?oc=5"
        },
        {
          "source": "미디어파인",
          "title_ko": "美 연준 콜린스 “인플레 안 꺾이면 금리 인상”, 시장도 긴축 가능성 주목",
          "original_url": "https://news.google.com/rss/articles/CBMibkFVX3lxTFBXYVV0M2FnZnZiNnFlcnB2alVpVFVnaGJvNGtYaFdPcHZ0M3JmQmk3TU9MUGFfSDA2b25EUWZqSDlOc2Rkb0g1TGtCYUNVM0J5dC1rdnhoNDd5aXBjdlZVRVFfeTY2WmpMWWl1eHVR?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMibkFVX3lxTFBXYVV0M2FnZnZiNnFlcnB2alVpVFVnaGJvNGtYaFdPcHZ0M3JmQmk3TU9MUGFfSDA2b25EUWZqSDlOc2Rkb0g1TGtCYUNVM0J5dC1rdnhoNDd5aXBjdlZVRVFfeTY2WmpMWWl1eHVR?oc=5"
        }
      ],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "Benzinga",
      "title_ko": "베센트의 국채 전략과 연준의 인플레 전쟁···케빈 워시가 짊어진 딜레마",
      "title_en": "",
      "summary_ko": "베센트의 국채 전략과 연준의 인플레 전쟁···케빈 워시가 짊어진 딜레마 Benzinga. 미 재무부의 TGA 현금 잔고 방출과 40조 달러 국가부채 조달(QRA) 사이클에 따른 국채 기간 프리미엄 및 글로벌 달러 유동성 환경에 직접적인 영향을 미칠 수 있습니다. Benzinga에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMivwJBVV95cUxQZDI2N0dwUHpuRTFQWEg1a3pIR3U2UmlTd1ZJeGFQNjY1MXE0c3N2VG4zSmdSZDVaWlhFdHhoZE9WMTRuVEV6QnJ2cHBic3A1TkZiaWE0R1M0T3RZRGVHUTVRcHlDelFQU1RMTmJ3a2pYemRQVmctaUtwWlZxaDFkeVdfRFRkV3dLdC05X29SZ2NOaUI1ZkVlUXYzUzZRdXBNN3RjUUU5YmpqalZqbDJNR0xyc3lWZWFDQVk3VDVValNWYzJtV3NjUmxVYnR5bUtnc2NpbHp1T3dqWUk1dmtVUHFrakEtcHU3b1FLVG84OE4yQ2NObDV6OUUtSW00c3AzVlZqQ0xMN2VPa1RXQ3pURlJwamdMdmMtaHJiUGY4cEJUcWZQMTlmc2FiLWt2Y2pUQzd6Y0RxeENYWTlzNF9Z?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMivwJBVV95cUxQZDI2N0dwUHpuRTFQWEg1a3pIR3U2UmlTd1ZJeGFQNjY1MXE0c3N2VG4zSmdSZDVaWlhFdHhoZE9WMTRuVEV6QnJ2cHBic3A1TkZiaWE0R1M0T3RZRGVHUTVRcHlDelFQU1RMTmJ3a2pYemRQVmctaUtwWlZxaDFkeVdfRFRkV3dLdC05X29SZ2NOaUI1ZkVlUXYzUzZRdXBNN3RjUUU5YmpqalZqbDJNR0xyc3lWZWFDQVk3VDVValNWYzJtV3NjUmxVYnR5bUtnc2NpbHp1T3dqWUk1dmtVUHFrakEtcHU3b1FLVG84OE4yQ2NObDV6OUUtSW00c3AzVlZqQ0xMN2VPa1RXQ3pURlJwamdMdmMtaHJiUGY4cEJUcWZQMTlmc2FiLWt2Y2pUQzd6Y0RxeENYWTlzNF9Z?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 35,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 26 Aug 2026 12:45:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "조선일보",
      "title_ko": "신현송 한은 총재가 말한 금리 인상 조건 셋 중 둘 ‘충족’…“백투백 금리 인상, 가능성 열려 있다”",
      "title_en": "",
      "summary_ko": "신현송 한은 총재가 말한 금리 인상 조건 셋 중 둘 ‘충족’…“백투백 금리 인상, 가능성 열려 있다” 조선일보. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 조선일보에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOanZKR0x2eEN5Tk1GelcwV245dThJUDl6M3pfX2dqZTM2SU1YdW9rSnZaS3BrY01OMGg1UG9hTFhILVBmSk5sSHhETjkxd2p0ZUFKZFlCdjRHQnNfVTJ1dWtxNDlVMjF3UWluS3kyOG9PdzZ2RlpDNVNWdjJpNGo5Qm9Nd1FUSDQyNEhmb1JR?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOanZKR0x2eEN5Tk1GelcwV245dThJUDl6M3pfX2dqZTM2SU1YdW9rSnZaS3BrY01OMGg1UG9hTFhILVBmSk5sSHhETjkxd2p0ZUFKZFlCdjRHQnNfVTJ1dWtxNDlVMjF3UWluS3kyOG9PdzZ2RlpDNVNWdjJpNGo5Qm9Nd1FUSDQyNEhmb1JR?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 30,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 26 Aug 2026 08:41:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "KB Think",
      "title_ko": "케빈 워시의 '소통 변화'…FOMC 회의록 뜯어보니 수치로 확인",
      "title_en": "",
      "summary_ko": "케빈 워시의 '소통 변화'…FOMC 회의록 뜯어보니 수치로 확인 KB Think. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. KB Think뿐만 아니라 OBC 뉴스 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMickFVX3lxTE9tQ1RvRkN5Q2pvRnc3Y0dCY3dFeG1oWVVwSzl5MnFFeEtwUHk4eXRFdUpwZllVdkhDYVF4bHlmUEJremppTTh6ekxWNXAxNTVIMGxtYUJHMFp2SzFwODZiUlU3YTNFeEFaUlp2NE9mOTVnZw?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMickFVX3lxTE9tQ1RvRkN5Q2pvRnc3Y0dCY3dFeG1oWVVwSzl5MnFFeEtwUHk4eXRFdUpwZllVdkhDYVF4bHlmUEJremppTTh6ekxWNXAxNTVIMGxtYUJHMFp2SzFwODZiUlU3YTNFeEFaUlp2NE9mOTVnZw?oc=5",
      "category": "fed_liquidity",
      "section_no": 2,
      "section_title": "연준 정책 및 유동성 동향",
      "section_icon": "🏛️",
      "importance_score": 30,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 26 Aug 2026 01:59:09 GMT",
      "related_articles": [
        {
          "source": "OBC 뉴스",
          "title_ko": "워시, 연준 ‘말수’ 확 줄였다…FOMC 회의록 18년 만에 최단",
          "original_url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE9UOTRTMl9UU3gzaWpwaUdwbkVKb2ZIenNYQVJ3M19YV1p6a01QSlVGSnlONUViLTJac3huT1p5VXhHZG03Snl0SkZMdE5IVWNfUlZMbU1fYVFJU0plb0x4dXByUkFZWnVTY0E?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE9UOTRTMl9UU3gzaWpwaUdwbkVKb2ZIenNYQVJ3M19YV1p6a01QSlVGSnlONUViLTJac3huT1p5VXhHZG03Snl0SkZMdE5IVWNfUlZMbU1fYVFJU0plb0x4dXByUkFZWnVTY0E?oc=5"
        }
      ],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "연합뉴스",
      "title_ko": "기준금리 인상? 인하?…트럼프·美연준 ’동상이몽’",
      "title_en": "",
      "summary_ko": "기준금리 인상? 인하?…트럼프·美연준 ’동상이몽’ 연합뉴스TV. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 연합뉴스뿐만 아니라 매일경제, 뉴스투데이 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5tMC1ZQjRndURiM2d6Y1ZYTDNEZ2RQV3p5bnpaemU1dlVFRUNVbVVnN1U0SV9JMjhBeWZHVGtmZHA3ZzYxM2FPWUp2ZFdac0c3Z0diUDNlcWdPalhiWkVVYjVabFJxRlU?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5tMC1ZQjRndURiM2d6Y1ZYTDNEZ2RQV3p5bnpaemU1dlVFRUNVbVVnN1U0SV9JMjhBeWZHVGtmZHA3ZzYxM2FPWUp2ZFdac0c3Z0diUDNlcWdPalhiWkVVYjVabFJxRlU?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 30,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Sun, 23 Aug 2026 04:39:00 GMT",
      "related_articles": [
        {
          "source": "뉴스투데이",
          "title_ko": "“기준금리 인상, 8월 아닌 10월에 할 듯”",
          "original_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9RbGZFbjF0WnBxdFIwVVZmZ0dKR19WUU0wSmx6NHFNRTM1LVI0VDFmRjMzZFllX014dl96Q3ZhLVN6UHRFMDAySkZfMGg5NG0tVlJxWDFRSjBRNG9MbkE?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9RbGZFbjF0WnBxdFIwVVZmZ0dKR19WUU0wSmx6NHFNRTM1LVI0VDFmRjMzZFllX014dl96Q3ZhLVN6UHRFMDAySkZfMGg5NG0tVlJxWDFRSjBRNG9MbkE?oc=5"
        },
        {
          "source": "매일경제",
          "title_ko": "韓 기준금리, 연속 인상이냐 동결이냐 … 신현송은 27일 금통위 직후 잭슨홀行",
          "original_url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE9WQjAyTlFfT3BmdjU5X0RLUGxINUczcU9KeklVTzhIbzlKc0E3ZGRoRFg1SHZ1X1NEYW1RTkgwOTctZnNzdkdTMlNoTmV5ajREVGZKZg?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE9WQjAyTlFfT3BmdjU5X0RLUGxINUczcU9KeklVTzhIbzlKc0E3ZGRoRFg1SHZ1X1NEYW1RTkgwOTctZnNzdkdTMlNoTmV5ajREVGZKZg?oc=5"
        }
      ],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "매일경제",
      "title_ko": "“대출이자 또 오르나”…내일 기준금리 ‘연속 인상’ 전문가 전망 엇갈려",
      "title_en": "",
      "summary_ko": "“대출이자 또 오르나”…내일 기준금리 ‘연속 인상’ 전문가 전망 엇갈려 매일경제. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 매일경제에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBXWmZXVlRKSmVWYVpiSm5paVpoNHUtVUJ6dk5oZ2VrRlptdy04aXhxM1pBcGdaZmFVQXlzLVpXaVpEbzMwQ0NIcXVoYUN1WUo2emdVbw?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTFBXWmZXVlRKSmVWYVpiSm5paVpoNHUtVUJ6dk5oZ2VrRlptdy04aXhxM1pBcGdaZmFVQXlzLVpXaVpEbzMwQ0NIcXVoYUN1WUo2emdVbw?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 26 Aug 2026 00:42:31 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "연합인포맥스",
      "title_ko": "채권시장 참여자 10명 중 8명 \"8월 금통위서 기준금리 동결 예상\"",
      "title_en": "",
      "summary_ko": "채권시장 참여자 10명 중 8명 \"8월 금통위서 기준금리 동결 예상\" 연합인포맥스. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 연합인포맥스에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9FMHlPVUs3OURyQlZ3Y3RpSjZtY2lrZF9PT3RGRGlkdDBYbElxckY4LWRWWHMwNkNlYm41blRBWHJ3ZjVGaVV3Wi1Ud1p1LThXLVhyaDdldy02UHphU2VtcFE0OEpRMVJ3QVdOT1A5OEI?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTE9FMHlPVUs3OURyQlZ3Y3RpSjZtY2lrZF9PT3RGRGlkdDBYbElxckY4LWRWWHMwNkNlYm41blRBWHJ3ZjVGaVV3Wi1Ud1p1LThXLVhyaDdldy02UHphU2VtcFE0OEpRMVJ3QVdOT1A5OEI?oc=5",
      "category": "korea_economy",
      "section_no": 5,
      "section_title": "국내 경제 관련 주요 뉴스 요약",
      "section_icon": "📈",
      "importance_score": 25,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Tue, 25 Aug 2026 02:25:48 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "YTN",
      "title_ko": "\"엔비디아·잭슨홀 주목\"...기준금리 결정도 관심",
      "title_en": "",
      "summary_ko": "\"엔비디아·잭슨홀 주목\"...기준금리 결정도 관심 YTN. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. YTN뿐만 아니라 YTN 등 주요 외신에서도 시장 파급력을 집중 분석하고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE02ZG1sMXE2M1FrdklpeTZhX2dlM0VPTmxmam1VZVpIbGZQSzRZX0h0LU9ETmp6UnFLNXBPS0hlODdVV1hOaGRMbkQ1YVdxd2ZhNlJaeTl4MkFXckFKbHc?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE02ZG1sMXE2M1FrdklpeTZhX2dlM0VPTmxmam1VZVpIbGZQSzRZX0h0LU9ETmp6UnFLNXBPS0hlODdVV1hOaGRMbkQ1YVdxd2ZhNlJaeTl4MkFXckFKbHc?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 55,
      "badge_label": "⭐ 주요 파도",
      "badge_class": "tier-wave",
      "pub_date": "Sun, 23 Aug 2026 14:24:00 GMT",
      "related_articles": [
        {
          "source": "YTN",
          "title_ko": "이번 주 엔비디아 실적 영향 관심...기준금리도 주목",
          "original_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE0yN1dqYmJZaEpXOXAyNk8wWkZreFUzQ1JTRWZmRVlZbnJYdjItSVhFYzlWVDBJcTI0alpyU0thb0dDb0ZMTjdLZmdNeFJlSTdkNC1tLW45NWhDb2MySXc?oc=5",
          "translated_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE0yN1dqYmJZaEpXOXAyNk8wWkZreFUzQ1JTRWZmRVlZbnJYdjItSVhFYzlWVDBJcTI0alpyU0thb0dDb0ZMTjdLZmdNeFJlSTdkNC1tLW45NWhDb2MySXc?oc=5"
        }
      ],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "이코노미스트",
      "title_ko": "‘엔비디아 실적·한은 기준금리’ 경계감에 몸사린 코스피 0.97% 상승 마감",
      "title_en": "",
      "summary_ko": "‘엔비디아 실적·한은 기준금리’ 경계감에 몸사린 코스피 0.97% 상승 마감 이코노미스트. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 이코노미스트에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE12ZE5fenBFaE9zek43al9Ubk9pZXZYOE0yc3l4U0l0dmluYVhDSXpQZ2hsOHdqdmRmTmtmOVBxajl5YnhqbG5NUXZBMDNIZzhMek03U19saExDUmFMcElpb2VR?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE12ZE5fenBFaE9zek43al9Ubk9pZXZYOE0yc3l4U0l0dmluYVhDSXpQZ2hsOHdqdmRmTmtmOVBxajl5YnhqbG5NUXZBMDNIZzhMek03U19saExDUmFMcElpb2VR?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 35,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 26 Aug 2026 06:59:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:47"
    },
    {
      "source": "Investing.com",
      "title_ko": "Nvidia 실적·연준 신호 앞두고 미국 증시 선물 보합세",
      "title_en": "",
      "summary_ko": "Nvidia 실적·연준 신호 앞두고 미국 증시 선물 보합세 Investing.com 한국어. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. Investing.com에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBRTFV6UzNvNmRwTEVvTDhXdk93bUcyZl9wWklHMnoweElvZWZZSlhRdDRVR0llVWNYU3lMVlgxbFVCT1Nfd2syQTFVckFaNUN6QzlKZXp1NzJna2xUcy1vcU50SDAyTk52UG9zaHItQjc?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMicEFVX3lxTFBRTFV6UzNvNmRwTEVvTDhXdk93bUcyZl9wWklHMnoweElvZWZZSlhRdDRVR0llVWNYU3lMVlgxbFVCT1Nfd2syQTFVckFaNUN6QzlKZXp1NzJna2xUcy1vcU50SDAyTk52UG9zaHItQjc?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 35,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Tue, 25 Aug 2026 01:05:00 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:48"
    },
    {
      "source": "머니투데이",
      "title_ko": "12시간 후 FOMC 의사록 공개…美 장기금리·반도체 흐름 변수 - 머니투데이",
      "title_en": "",
      "summary_ko": "12시간 후 FOMC 의사록 공개…美 장기금리·반도체 흐름 변수 - 머니투데이 관련 핵심 동향이 발표되었습니다. 연준(Fed)의 기준금리 경로 및 인플레이션 둔화 속도와 직결되는 사안으로, 향후 글로벌 채권 금리 안정과 주식 밸류에이션 부담 완화 여부에 핵심 변수로 작용합니다. 머니투데이에 따르면 시장 참여자들의 기대치 변화와 향후 정책 발표 일정에 관심이 집중되고 있습니다.",
      "original_url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFBBejFOZUg5eW5JaGdDb084UjJwR0Z5Qzg0UXVuWU0zdGFQX3YwVE9GNjEtb2VZUW1Zc3dTeGhEcTE2ZFl4TkhXNHJiQU1tU2hsSU1fSGFEcXJ4ZkttSjBNRXJ3ajQteWFJ0gFuQVVfeXFMTmtNODZfZFlSanR4M0lPTl91QWJzQ1lhT0ZOLU9IaHcwUzVCUDhWb3JXRzJuZnJLbXBkeDR2RDBhb1pwVE9xc21fdXNLYUltUlNoY3dYdEQyb2RkSTZNOGppWjl2RHNlekhxbTZMY1E?oc=5",
      "translated_url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTFBBejFOZUg5eW5JaGdDb084UjJwR0Z5Qzg0UXVuWU0zdGFQX3YwVE9GNjEtb2VZUW1Zc3dTeGhEcTE2ZFl4TkhXNHJiQU1tU2hsSU1fSGFEcXJ4ZkttSjBNRXJ3ajQteWFJ0gFuQVVfeXFMTmtNODZfZFlSanR4M0lPTl91QWJzQ1lhT0ZOLU9IaHcwUzVCUDhWb3JXRzJuZnJLbXBkeDR2RDBhb1pwVE9xc21fdXNLYUltUlNoY3dYdEQyb2RkSTZNOGppWjl2RHNlekhxbTZMY1E?oc=5",
      "category": "ai_hegemony",
      "section_no": 6,
      "section_title": "AI 패권 전쟁 & 반도체·전력 인프라 동향",
      "section_icon": "🤖",
      "importance_score": 30,
      "badge_label": "📌 체크",
      "badge_class": "tier-check",
      "pub_date": "Wed, 19 Aug 2026 07:14:50 GMT",
      "related_articles": [],
      "crawled_at": "2026-08-26 21:54:48"
    }
  ]
};
window.__KEYWORDS_CONFIG__ = {
  "score_threshold": 20,
  "swell_keywords": [
    "tga",
    "재무부 일반계정",
    "현금 잔고",
    "스콧 베센트",
    "베센트",
    "40조",
    "40 trillion",
    "국가부채",
    "national debt",
    "부채 한도",
    "debt ceiling",
    "스테이블코인",
    "stablecoin",
    "테더",
    "서클",
    "단기국채",
    "t-bills",
    "hbm",
    "엔비디아",
    "nvidia",
    "tsmc",
    "딥시크",
    "deepseek",
    "전력망",
    "power grid",
    "변압기",
    "transformer",
    "smr",
    "원전",
    "구리",
    "copper",
    "닥터 코퍼",
    "전력",
    "전력난",
    "전력 부족",
    "power shortage",
    "electricity",
    "희토류",
    "히토류",
    "rare earth",
    "rare earths",
    "핵심광물",
    "critical minerals",
    "그린란드",
    "greenland",
    "1500원",
    "1600원",
    "패권",
    "이란",
    "iran",
    "호르무즈",
    "hormuz",
    "strait of hormuz",
    "중동",
    "middle east",
    "우크라이나",
    "ukraine",
    "러시아 우크라이나",
    "russia ukraine",
    "지정학"
  ],
  "impact_keywords": [
    "fomc",
    "금리 결정",
    "금리 인하",
    "금리 인상",
    "rate cut",
    "rate hike",
    "파월",
    "powell",
    "긴급",
    "shock",
    "쇼크",
    "surprise",
    "서프라이즈",
    "사상 최대",
    "record high",
    "경고",
    "warning",
    "폭등",
    "폭락",
    "crash",
    "surge",
    "순매도",
    "순매수",
    "외국인"
  ]
};
window.__SOURCES_CONFIG__ = [
  {
    "id": "fed_official",
    "name": "🏛️ 미국 연방준비제도 (Federal Reserve)",
    "website": "https://www.federalreserve.gov",
    "domain": "federalreserve.gov",
    "description": "연준 공식 성명서, 통화정책 결정문, 파월 의장 연설문 및 베이지북",
    "enabled": true
  },
  {
    "id": "ny_fed",
    "name": "📑 뉴욕 연방준비은행 (NY Fed Liberty Street)",
    "website": "https://libertystreeteconomics.newyorkfed.org",
    "domain": "libertystreeteconomics.newyorkfed.org",
    "description": "뉴욕 연은 유동성, 재정적자, 국채 시장 심층 연구 리포트",
    "enabled": true
  },
  {
    "id": "bloomberg",
    "name": "🌐 Bloomberg (블룸버그)",
    "website": "https://www.bloomberg.com",
    "domain": "bloomberg.com",
    "description": "글로벌 1티어 경제 매체 (거시경제, 연준 금리, 채권, 원자재, 빅테크)",
    "enabled": true
  },
  {
    "id": "reuters",
    "name": "🌐 Reuters (로이터 통신)",
    "website": "https://www.reuters.com",
    "domain": "reuters.com",
    "description": "글로벌 통화정책, 중앙은행 금리 결정, 지정학 긴급 속보",
    "enabled": true
  },
  {
    "id": "wsj",
    "name": "🇺🇸 Wall Street Journal (월스트리트저널)",
    "website": "https://www.wsj.com",
    "domain": "wsj.com",
    "description": "미국 실물 경제, 40조 달러 국가부채, 재무부 국채 발행(QRA), 기업 동향",
    "enabled": true
  },
  {
    "id": "cnbc",
    "name": "📺 CNBC (미국 CNBC)",
    "website": "https://www.cnbc.com",
    "domain": "cnbc.com",
    "description": "미국 금융시장 실시간 거시, 채권수익률, 환율, 고용/소비자물가(CPI)",
    "enabled": true
  },
  {
    "id": "ft",
    "name": "🇬🇧 Financial Times (파이낸셜타임스)",
    "website": "https://www.ft.com",
    "domain": "ft.com",
    "description": "영국/유럽 및 글로벌 매크로 경제, 국제 금융시장 심층 분석",
    "enabled": true
  },
  {
    "id": "economist",
    "name": "🇬🇧 The Economist (이코노미스트)",
    "website": "https://www.economist.com",
    "domain": "economist.com",
    "description": "글로벌 매크로 메가트렌드, 지정학 구조 분석 및 경제 전망",
    "enabled": true
  },
  {
    "id": "nytimes_biz",
    "name": "📰 New York Times Business (뉴욕타임스)",
    "website": "https://www.nytimes.com/section/business",
    "domain": "nytimes.com",
    "description": "미국 경제정책, 무역 갈등, 테크 산업 규제 및 거시 트렌드",
    "enabled": true
  },
  {
    "id": "ecb",
    "name": "🇪🇺 ECB (유럽중앙은행)",
    "website": "https://www.ecb.europa.eu",
    "domain": "ecb.europa.eu",
    "description": "유로존 기준금리 결정, 유럽 물가 및 통화정책 공식 발표",
    "enabled": true
  },
  {
    "id": "boj",
    "name": "🇯🇵 BOJ (일본은행)",
    "website": "https://www.boj.or.jp",
    "domain": "boj.or.jp",
    "description": "일본은행 금리 결정, 엔화 정책, 엔캐리 트레이드 관련 공식 발표",
    "enabled": true
  },
  {
    "id": "nikkei",
    "name": "🇯🇵 Nikkei Asia (닛케이 아시아)",
    "website": "https://asia.nikkei.com",
    "domain": "asia.nikkei.com",
    "description": "아시아 경제, 글로벌 반도체/HBM 공급망, 아시아 환율 동향",
    "enabled": true
  },
  {
    "id": "caixin",
    "name": "🇨🇳 Caixin Global (중국 차이신)",
    "website": "https://www.caixinglobal.com",
    "domain": "caixinglobal.com",
    "description": "중국 실물 경제지표, 부동산 부채, 통화정책 및 금융시장 전문",
    "enabled": true
  },
  {
    "id": "scmp",
    "name": "🇨🇳 SCMP (사우스차이나모닝포스트)",
    "website": "https://www.scmp.com",
    "domain": "scmp.com",
    "description": "중국 거시경제, 미중 기술/원자재 패권 갈등, 위안화 환율",
    "enabled": true
  },
  {
    "id": "goldman_sachs",
    "name": "📊 Goldman Sachs Research (골드만삭스)",
    "website": "https://www.goldmansachs.com/insights",
    "domain": "goldmansachs.com",
    "description": "월가 대표 투자은행 글로벌 거시 전망 및 섹터별 인사이트 리포트",
    "enabled": true
  },
  {
    "id": "imf",
    "name": "🌐 IMF (국제통화기금)",
    "website": "https://www.imf.org",
    "domain": "imf.org",
    "description": "글로벌 금융안정 보고서(GFSR), 세계 경제성장률 전망(WEO)",
    "enabled": true
  },
  {
    "id": "bis",
    "name": "🌐 BIS (국제결제은행)",
    "website": "https://www.bis.org",
    "domain": "bis.org",
    "description": "중앙은행들의 중앙은행, 글로벌 잉여 유동성 및 은행 건전성 분석",
    "enabled": true
  },
  {
    "id": "bok",
    "name": "🏛️ 한국은행 (Bank of Korea)",
    "website": "https://www.bok.or.kr",
    "domain": "bok.or.kr",
    "description": "금융통화위원회 기준금리 결정, 국내 경제전망 및 통화신용정책 보고서",
    "enabled": true
  },
  {
    "id": "einfomax",
    "name": "🇰🇷 연합인포맥스",
    "website": "https://news.einfomax.co.kr",
    "domain": "einfomax.co.kr",
    "description": "외환(달러/원), 채권 금리, 외국인 순매수/선물 수급 실시간 전문",
    "enabled": true
  },
  {
    "id": "hankyung",
    "name": "🇰🇷 한국경제신문 (한경)",
    "website": "https://www.hankyung.com",
    "domain": "hankyung.com",
    "description": "국내외 증시, 반도체/수출입, 거시경제 및 부동산/가계부채 동향",
    "enabled": true
  },
  {
    "id": "mk",
    "name": "🇰🇷 매일경제신문 (매경)",
    "website": "https://www.mk.co.kr",
    "domain": "mk.co.kr",
    "description": "국내외 거시경제, 외환 및 증시, 기업 투자 사이클 심층 보도",
    "enabled": true
  },
  {
    "id": "yna",
    "name": "🇰🇷 연합뉴스 (경제/금융)",
    "website": "https://www.yna.co.kr",
    "domain": "yna.co.kr",
    "description": "국내 수출입 펀더멘털, 소비자물가(CPI), 정부 경제재정 정책 속보",
    "enabled": true
  },
  {
    "id": "chosunbiz",
    "name": "🇰🇷 조선비즈",
    "website": "https://biz.chosun.com",
    "domain": "chosunbiz.com",
    "description": "국내외 거시경제, IT/반도체 산업, 금융 및 글로벌 공급망",
    "enabled": true
  },
  {
    "id": "the_information",
    "name": "🤖 The Information / Tech (실리콘밸리 테크)",
    "website": "https://www.theinformation.com",
    "domain": "theinformation.com",
    "description": "글로벌 AI 빅테크, AI 칩(GPU/HBM), 데이터센터 전력 인프라 특종 보도",
    "enabled": true
  }
];
